[build]
  base = "SPORTIQ_SPRINT_2B_MATCH_SETUP"
  command = "flutter build web --release"
  publish = "build/web"

[[plugins]]
  package = "netlify-plugin-flutter"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200